version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch-browsers
    working_directory: ~/project/
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: npm install
      - run:
          name: 'Push to UXPin'
          command: node --max-old-space-size=4096 ./node_modules/.bin/uxpin-merge push --webpack-config ./webpack.config.uxpin.js --wrapper ./tools/UXPinWrapper.js --token 46ee77f72f2f9f221185e790e8e65cce97fcc0d6
